name: CI-Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_DIR: ${{github.workspace}}/_build

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.26.1'

    - name: Check cmake version
      run: cmake --version

    - name: Configure CMake
      run: |
        mkdir "${{env.BUILD_DIR}}"
        cd "${{env.BUILD_DIR}}"
        cmake .. ^
          "-DCMAKE_SYSTEM_NAME=Android" ^
          "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
          "-DCMAKE_SYSTEM_VERSION=21" ^
          "-DANDROID_PLATFORM=android-21" ^
          "-DANDROID_ABI=arm64-v8a" ^
          "-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a" ^
          "-DANDROID_NDK=%ANDROID_NDK_HOME%" ^
          "-DCMAKE_ANDROID_NDK=%ANDROID_NDK_HOME%" ^
          "-DCMAKE_TOOLCHAIN_FILE=%ANDROID_NDK_HOME%\\build\\cmake\\android.toolchain.cmake" ^
          "-DCMAKE_MAKE_PROGRAM=%ANDROID_HOME%\\cmake\\3.22.1\\bin\\ninja.exe" ^
          "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=${{github.workspace}}/_build/droid" ^
          "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{github.workspace}}/_build/droid" ^
          "-DCMAKE_BUILD_TYPE=Debug" ^
          -GNinja ^
          "-DANDROID_STL=c++_shared" ^
          "-DSFML_STATIC_LIBRARIES=OFF"
      shell: cmd

    - name: Build
      working-directory: ${{env.BUILD_DIR}}
      run: |
        cmake --build .
      shell: cmd
